layout_spectrum: 0.7834888
typography_spectrum: 0.2741935
color:
  saturation: 0.9217443
  brandStrength: 0.6153885
  lightness: 0.8691756
  rhythmicContrast: 0.8787335
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: NonStopTravel
